AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  splatoon-schedule-alex-skill

Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Tracing: Active

Resources:
  ScheduleFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - arm64
      Environment:
        Variables:
          LAMBDA_TASK_ROOT: /var/task
          LAMBDA_RUNTIME_DIR: /var/runtime